### ISSUE TITLE
libwrap conflict with tcp-wrappers

### ISSUE THREAD

**Issue by sarnold** [grate-driver/grate#1]
I'm running grate under Gentoo arm on a trimslice.  Trying to install grate aborts due to a file collision:
- Detected file collision(s):
- 
-      /usr/lib/libwrap.so
- 
- Searching all installed packages for file collisions...
- 
- Press Ctrl-C to Stop
- 
- sys-apps/tcp-wrappers-7.6.22-r1:0::gentoo
-      /usr/lib/libwrap.so
- 
- Package 'media-libs/grate-9999' NOT merged due to file collisions. If
- necessary, refer to your elog messages for the whole content of the
- above message.

> > > Failed to install media-libs/grate-9999, Log file:

**Comment by kusma** [comment]
Hmm, interesting. I never installed grate, as it's not really useful for me installed. What was your motivation for you to install?

Perhaps libwrap should be marked as noinst? @thierryreding, what do you think?

**Comment by thierryreding** [comment]
I don't think marking libwrap as noinst will work, since that typically results in automake building it as a static library, which will prevent it from being used with LD_PRELOAD. Perhaps namespacing it as libgrate-wrap.so would work?

**Comment by kusma** [comment]
Ah, true. Yeah, perhaps that's better.

**Comment by sarnold** [comment]
The goal for the trimslice is a fully open source tegra build for xorg and weston/wayland.  Still using both the main portage tree and my overlays, but it's on full mainline kernel (using gentoo-sources) and device tree u-boot.  Of all my arm machines, this one is the only one close to "fully open source"...

**Comment by kusma** [comment]
Fixed.
