### ISSUE TITLE
Hi trying just ro run this on beaglebone 

### ISSUE THREAD

**Issue by ghost** [grate-driver/grate#70]
Linux beaglebone 4.14.108-ti-r108
Debian GNU/Linux 9 \n \l
BeagleBoard.org Debian Image 2019-06-30

The qt QML dashboard/extras/dashboard/dashboard  which is a pure EGL app works,
while this example 
```
gcc ./main.c -o tri -lEGL -lGLESv2
debian@beaglebone:~/TRI$ ./tri 
EGL: 1.4
config:0x1 num_config:0
failed to create context
```

Thank you
.

**Comment by digetx** [comment]
Maybe you need to pass `DISPLAY=:0` or something like that in the environment variables? This is needed if you're running Xorg manually, i.e. not using some Desktop Environment. In a case of DE, you'll probably need to run it from a the DE itself (depends on the Display Manager).

**Comment by ghost** [comment]
Hi, Thank you. There is noX11 no wayland, no graphic server.
Got it...GL_CONTEXT_CLIENT_VERSION, 1,

**Comment by ghost** [comment]
Got it...GL_CONTEXT_CLIENT_VERSION, 1
